View existing action rules
ONSdigital/rasrm-ops pull request #7
Opened 2018-11-20 15:01 UTC by liamtoozer

# Motivation and Context

Quick addition to show any action plans for an existing collection exercise. This prevents the need to connect to a database to check which action plans have been created.

# What has changed

* Changed the UI to show action rules in the Action creation page
* Updated existing test.
* Small refactor to move related service calls into controllers.

# How to test?

* Checkout this branch and start the UI (ensure other services are running locally).
* Click an existing survey.
* Click a collection exercise (or create a new one).
* Click **View / Load Action Plans** and create a new action plan.
* Ensure the action plan you created appears when you return to the above page.

# Screenshots (if appropriate):
Should look something similar to this:
<img width="560" alt="screenshot 2018-11-20 at 14 42 07" src="https://user-images.githubusercontent.com/23473592/48780740-81d04f00-ecd2-11e8-8c6b-bb6ebf94f0c0.png">

2018-11-21 10:00 UTC, hbrace requested changes
![image](https://user-images.githubusercontent.com/43209528/48833851-37071380-ed74-11e8-8d2c-69a223cef489.png)

Failure when running make docker, appears there is an errant blank line!

2018-11-21 14:13 UTC, hbrace approved these changes

2018-11-21 14:14 UTC, hbrace commented
Looks good to me 👍

2018-11-22 14:26 UTC, AdamHawtin approved these changes

2018-11-22 15:53 UTC, liamtoozer commented
Last commit was from feedback from @AdamHawtin 👍

2018-11-22 15:54 UTC, merged